"""Public contracts for framework-neutral model-weight resharding."""

from .manifest import (
    OwnershipAxis,
    ParallelRank,
    ParallelTopology,
    PlacementFragment,
    ReplicatedAxis,
    RuntimeBindingFragment,
    SplitAxis,
    TensorDescriptor,
    TopologyParticipant,
    WeightPlacementManifest,
    WeightPlacementPart,
    WeightRuntimeBindingManifest,
    validate_runtime_binding,
    validate_runtime_bindings,
)
from .serde import weight_placement_from_json, weight_placement_to_json
from .planner import (
    BoundWeightFragment,
    CopyRange,
    ExecutorTransferPlan,
    LogicalTransferPlan,
    PipelineRouteGroup,
    PlacementExecutorPlan,
    RuntimeLeaseSnapshot,
    RuntimeBindingAttestation,
    TransferPlan,
    TransferRegion,
    bind_logical_transfer_plan,
    plan_placement_transfer,
    plan_placement_transfer_to_local_target,
    resolve_executor_plan,
    resolve_executor_plans,
)


__all__ = [
    "ParallelRank",
    "ParallelTopology",
    "PlacementFragment",
    "WeightPlacementManifest",
    "WeightPlacementPart",
    "RuntimeBindingFragment",
    "WeightRuntimeBindingManifest",
    "SplitAxis",
    "ReplicatedAxis",
    "OwnershipAxis",
    "TensorDescriptor",
    "TopologyParticipant",
    "validate_runtime_binding",
    "validate_runtime_bindings",
    "weight_placement_from_json",
    "weight_placement_to_json",
    "BoundWeightFragment",
    "CopyRange",
    "ExecutorTransferPlan",
    "LogicalTransferPlan",
    "PipelineRouteGroup",
    "PlacementExecutorPlan",
    "RuntimeLeaseSnapshot",
    "RuntimeBindingAttestation",
    "TransferPlan",
    "TransferRegion",
    "bind_logical_transfer_plan",
    "plan_placement_transfer",
    "plan_placement_transfer_to_local_target",
    "resolve_executor_plan",
    "resolve_executor_plans",
]
