if(IBVERBS_INCLUDE)
  file(GLOB XPORT_SOURCES "*.cpp")
  add_library(tent_xport_rdma STATIC ${XPORT_SOURCES})
  target_include_directories(tent_xport_rdma PUBLIC ${IBVERBS_INCLUDE})
  target_link_libraries(tent_xport_rdma PUBLIC tent_common)
  if(MOONCAKE_ENABLE_ADAPTIVE_CC)
    target_link_libraries(tent_xport_rdma
                          PUBLIC adaptive_congestion_control_core)
  endif()
endif()
